"""Update Invoice model

Revision ID: 0c3a13fda4a3
Revises: f81bd0b8d659
Create Date: 2024-10-10 21:40:47.630747

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0c3a13fda4a3'
down_revision = 'f81bd0b8d659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        # Remove the line that adds 'patient_name' as it already exists
        # batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=False))
        
        # Check if columns exist before adding them
        columns = [column.name for column in sa.Table('invoice', sa.MetaData(), autoload_with=op.get_bind()).columns]
        
        if 'patient_email' not in columns:
            batch_op.add_column(sa.Column('patient_email', sa.String(length=120), nullable=False))
        if 'patient_address' not in columns:
            batch_op.add_column(sa.Column('patient_address', sa.String(length=200), nullable=False))
        if 'additional_notes' not in columns:
            batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('patient_address')
        batch_op.drop_column('patient_email')
    # ### end Alembic commands ###
