"""Initial migration

Revision ID: 1aa03541e6a3
Revises: 
Create Date: 2024-10-06 02:35:35.458659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa03541e6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_record_number', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.drop_column('medical_record_number')

    # ### end Alembic commands ###
