"""Add payment_currency to BillingRecord

Revision ID: 70c7eb9ef20c
Revises: 1aa03541e6a3
Create Date: 2024-10-06 02:46:29.348144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c7eb9ef20c'
down_revision = '1aa03541e6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.drop_column('payment_currency')
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
